### ISSUE TITLE
check php-fpm configuration

### ISSUE THREAD

**Issue by Cinux90** [while-true-do/ansible-role-php#6]
### Type of Report

enhancement 

### Actual behaviour

No check that the configuration is fine.

### Expected behaviour

a validate action for the template task in the php-fpm.yml file.
e.g.:
```
- name: Configure /etc/php-fpm.d/www.conf
  template:
    src: www.conf.j2
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644
    validate: 'php-fpm -y %s -t'
  notify:
    - Restart PHP-FPM
```
